/**
 * Hanzo UI - Code Components Registry
 *
 * Code editing, viewing, and developer tool components.
 * These are Hanzo-exclusive extensions for developer experiences.
 */

import { type Registry, type RegistryItem } from "../schema"

const code: RegistryItem[] = [
  {
    name: "code-block",
    type: "registry:code",
    title: "Code Block",
    description: "Syntax highlighted code block with copy functionality",
    dependencies: ["@hanzo/ui", "shiki", "react-copy-to-clipboard"],
    files: [{ path: "code/code-block.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "display",
  },
  {
    name: "code-editor",
    type: "registry:code",
    title: "Code Editor",
    description: "Full-featured code editor with syntax highlighting and IntelliSense",
    dependencies: ["@hanzo/ui", "@monaco-editor/react"],
    files: [{ path: "code/code-editor.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "editor",
  },
  {
    name: "code-compare",
    type: "registry:code",
    title: "Code Compare",
    description: "Side-by-side code comparison view",
    dependencies: ["@hanzo/ui", "react-diff-viewer"],
    files: [{ path: "code/code-compare.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "diff",
  },
  {
    name: "code-diff",
    type: "registry:code",
    title: "Code Diff",
    description: "Code difference viewer with inline highlighting",
    dependencies: ["@hanzo/ui", "diff"],
    files: [{ path: "code/code-diff.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "diff",
  },
  {
    name: "code-explorer",
    type: "registry:code",
    title: "Code Explorer",
    description: "File tree and code explorer interface",
    dependencies: ["@hanzo/ui", "@monaco-editor/react"],
    registryDependencies: ["tree"],
    files: [{ path: "code/code-explorer.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "navigation",
  },
  {
    name: "code-preview",
    type: "registry:code",
    title: "Code Preview",
    description: "Live code preview with editing",
    dependencies: ["@hanzo/ui", "react-live"],
    files: [{ path: "code/code-preview.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "preview",
  },
  {
    name: "code-snippet",
    type: "registry:code",
    title: "Code Snippet",
    description: "Inline code snippet with syntax highlighting",
    dependencies: ["@hanzo/ui", "prism-react-renderer"],
    files: [{ path: "code/code-snippet.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "display",
  },
  {
    name: "code-terminal",
    type: "registry:code",
    title: "Code Terminal",
    description: "Terminal-style code interface with command history",
    dependencies: ["@hanzo/ui", "xterm", "xterm-addon-fit"],
    files: [{ path: "code/code-terminal.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "terminal",
  },
  {
    name: "terminal",
    type: "registry:code",
    title: "Terminal",
    description: "Full terminal emulator component",
    dependencies: ["@hanzo/ui", "xterm", "xterm-addon-fit", "xterm-addon-web-links"],
    files: [{ path: "code/terminal.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "terminal",
  },
  {
    name: "code-tabs",
    type: "registry:code",
    title: "Code Tabs",
    description: "Tabbed code blocks for multiple files or languages",
    dependencies: ["@hanzo/ui", "shiki"],
    registryDependencies: ["tabs"],
    files: [{ path: "code/code-tabs.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "display",
  },
  {
    name: "code-sandbox",
    type: "registry:code",
    title: "Code Sandbox",
    description: "Embedded code sandbox for live editing and preview",
    dependencies: ["@hanzo/ui", "@codesandbox/sandpack-react"],
    files: [{ path: "code/code-sandbox.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "preview",
  },
  {
    name: "code-annotation",
    type: "registry:code",
    title: "Code Annotation",
    description: "Code block with inline annotations and comments",
    dependencies: ["@hanzo/ui", "shiki"],
    files: [{ path: "code/code-annotation.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "display",
  },
  {
    name: "code-highlight",
    type: "registry:code",
    title: "Code Highlight",
    description: "Code with line and word highlighting",
    dependencies: ["@hanzo/ui", "shiki"],
    files: [{ path: "code/code-highlight.tsx", type: "registry:code" }],
    category: "code",
    subcategory: "display",
  },
]

export const hanzoCodeRegistry: Registry = {
  name: "hanzo/ui/code",
  homepage: "https://ui.hanzo.ai/code",
  items: code,
}
